name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Test

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v4

      - name: Use Node.js v24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Validate Dependencies
        uses: https://github.com/naomi-lgbt/dependency-pin-check
        with:
            dev-dependencies: true
            peer-dependencies: true
            optional-dependencies: true

      - name: Build
        run: npm run build